name: amur-dev-deploy
on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, synchronize]
    branches:
      - master

jobs:
  version:
    uses: proxima-one/github-workflows/.github/workflows/version.yml@master
    with:
      appName: state-manager
      dockerRepo: "proxima.one/services"
    secrets:
      DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}

  publish:
    if: ${{ github.event_name == 'push' }}
    uses: proxima-one/github-workflows/.github/workflows/docker-publish.yml@master
    needs: version
    with:
      dockerfilePath: ./deployment/Dockerfile
      imageId: ${{ needs.version.outputs.imageId }}
      version: ${{ needs.version.outputs.version }}
    secrets:
      DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  pulumi:
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.base_ref == 'master') }}
    needs: [version, publish]
    uses: proxima-one/github-workflows/.github/workflows/pulumi-service.yml@master
    with:
      stack: "proxima-one/amur-dev"
      pulumiPath: ./deployment
      preview: ${{ github.event_name == 'pull_request' }}
      publishedImageId: ${{ needs.version.outputs.imageId }}
      publishedVersion: ${{ needs.version.outputs.version }}
    secrets:
      DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
      CI_NPM_TOKEN: ${{ secrets.CI_NPM_TOKEN }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
