name: client-check-version
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
    paths:
      - "proto/**"
      - "client-ts/**"

jobs:
  check_version:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client-ts
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Check versions"
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 --match="client-v*")
          LATEST_VERSION=${LATEST_TAG:8}
          NEW_VERSION=$(jq < package.json ".version" --raw-output)
          echo "Latest version: $LATEST_VERSION"
          echo "New version: $NEW_VERSION"
          if [[ $NEW_VERSION == $LATEST_VERSION ]]; then
            echo "::error ::New package version was not set"
            exit 1
          fi
