name: amur-deploy
on:
  workflow_dispatch:

jobs:
  version:
    uses: proxima-one/github-workflows/.github/workflows/version.yml@master
    with:
      appName: state-manager
      dockerRepo: "proxima.one/services"
    secrets:
      DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}

  pulumi:
    needs: version
    uses: proxima-one/github-workflows/.github/workflows/pulumi-service.yml@master
    with:
      stack: "proxima-one/amur"
      pulumiPath: ./deployment
      preview: false
      publishedImageId: ${{ needs.version.outputs.imageId }}
      publishedVersion: ${{ needs.version.outputs.version }}
    secrets:
      DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
      CI_NPM_TOKEN: ${{ secrets.CI_NPM_TOKEN }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
